name: Release to CurseForge

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Get mod properties
        id: mod_props
        run: |
          echo "VERSION=$(grep '^version=' gradle.properties | cut -d'=' -f2)" >> $GITHUB_OUTPUT

      - name: Build
        run: chmod +x ./gradlew && ./gradlew build

      # --- Fabric 1.21.11 ---
      - name: Publish Fabric 1.21.11 to CurseForge
        uses: itsmeow/curseforge-upload@v3
        with:
          token: ${{ secrets.CF_API_TOKEN }}
          project_id: 1483308
          game_endpoint: minecraft
          file_path: fabric-1.21.11/build/libs/tatamicraft-fabric-1.21.11-${{ steps.mod_props.outputs.VERSION }}.jar
          display_name: TatamiCraft ${{ steps.mod_props.outputs.VERSION }} (Fabric 1.21.11)
          game_versions: Minecraft 1.21:1.21.11,Java 21,Fabric
          changelog: Release version ${{ steps.mod_props.outputs.VERSION }}
          changelog_type: text

      # --- NeoForge 1.21.11 ---
      - name: Publish NeoForge 1.21.11 to CurseForge
        uses: itsmeow/curseforge-upload@v3
        with:
          token: ${{ secrets.CF_API_TOKEN }}
          project_id: 1483308
          game_endpoint: minecraft
          file_path: neoforge-1.21.11/build/libs/tatamicraft-neoforge-1.21.11-${{ steps.mod_props.outputs.VERSION }}.jar
          display_name: TatamiCraft ${{ steps.mod_props.outputs.VERSION }} (NeoForge 1.21.11)
          game_versions: Minecraft 1.21:1.21.11,Java 21,NeoForge
          changelog: Release version ${{ steps.mod_props.outputs.VERSION }}
          changelog_type: text

      ###
      # 1.20.1 still doesn't work yet.
      ###

      # --- Fabric 1.20.1 ---
#      - name: Publish Fabric 1.20.1 to CurseForge
#        uses: itsmeow/curseforge-upload@v3
#        with:
#          token: ${{ secrets.CF_API_TOKEN }}
#          project_id: 1483308
#          game_endpoint: minecraft
#          file_path: fabric-1.20.1/build/libs/tatamicraft-fabric-1.20.1-${{ steps.mod_props.outputs.VERSION }}.jar
#          display_name: TatamiCraft ${{ steps.mod_props.outputs.VERSION }} (Fabric 1.20.1)
#          game_versions: Minecraft 1.20:1.20.1,Java 17,Fabric
#          changelog: Release version ${{ steps.mod_props.outputs.VERSION }}
#          changelog_type: text

      # --- Forge 1.20.1 ---
#      - name: Publish Forge 1.20.1 to CurseForge
#        uses: itsmeow/curseforge-upload@v3
#        with:
#          token: ${{ secrets.CF_API_TOKEN }}
#          project_id: 1483308
#          game_endpoint: minecraft
#          file_path: neoforge-1.20.1/build/libs/tatamicraft-neoforge-1.20.1-${{ steps.mod_props.outputs.VERSION }}.jar
#          display_name: TatamiCraft ${{ steps.mod_props.outputs.VERSION }} (Forge 1.20.1)
#          game_versions: Minecraft 1.20:1.20.1,Java 17,Forge
#          changelog: Release version ${{ steps.mod_props.outputs.VERSION }}
#          changelog_type: text
