name: Release to Modrinth

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Get mod properties
        id: mod_props
        run: |
          echo "VERSION=$(grep '^version=' gradle.properties | cut -d'=' -f2)" >> $GITHUB_OUTPUT

      - name: Build
        run: chmod +x ./gradlew && ./gradlew build

      # --- Fabric 1.21.11 ---
      - name: Publish Fabric 1.21.11 to Modrinth
        uses: cloudnode-pro/modrinth-publish@v2
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: 8L1DTZf2
          version: ${{ steps.mod_props.outputs.VERSION }}+fabric-1.21.11
          loaders: fabric
          game-versions: 1.21.11
          files: "fabric-1.21.11/build/libs/tatamicraft-fabric-1.21.11-${{ steps.mod_props.outputs.VERSION }}.jar"
          changelog: "Release version ${{ steps.mod_props.outputs.VERSION }}"

      # --- NeoForge 1.21.11 ---
      - name: Publish NeoForge 1.21.11 to Modrinth
        uses: cloudnode-pro/modrinth-publish@v2
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: 8L1DTZf2
          version: ${{ steps.mod_props.outputs.VERSION }}+neoforge-1.21.11
          loaders: neoforge
          game-versions: 1.21.11
          files: "neoforge-1.21.11/build/libs/tatamicraft-neoforge-1.21.11-${{ steps.mod_props.outputs.VERSION }}.jar"
          changelog: "Release version ${{ steps.mod_props.outputs.VERSION }}"

      # --- Fabric 1.20.1 ---
      - name: Publish Fabric 1.20.1 to Modrinth
        uses: cloudnode-pro/modrinth-publish@v2
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: 8L1DTZf2
          version: ${{ steps.mod_props.outputs.VERSION }}+fabric-1.20.1
          loaders: fabric
          game-versions: 1.20.1
          files: "fabric-1.20.1/build/libs/tatamicraft-fabric-1.20.1-${{ steps.mod_props.outputs.VERSION }}.jar"
          changelog: "Release version ${{ steps.mod_props.outputs.VERSION }}"

      # --- Forge 1.20.1 ---
      - name: Publish Forge 1.20.1 to Modrinth
        uses: cloudnode-pro/modrinth-publish@v2
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: 8L1DTZf2
          version: ${{ steps.mod_props.outputs.VERSION }}+forge-1.20.1
          loaders: forge
          game-versions: 1.20.1
          files: "neoforge-1.20.1/build/libs/tatamicraft-neoforge-1.20.1-${{ steps.mod_props.outputs.VERSION }}.jar"
          changelog: "Release version ${{ steps.mod_props.outputs.VERSION }}"
